openapi: 3.0.3
info:
  title: Pixel Grid Service 
  description: |-
    This is the API of a Pixel Grid service
  # termsOfService: http://swagger.io/terms/
  contact:
    email: a.ricci@unibo.it
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.0
# externalDocs:
#  description: Find out more about Swagger
#  url: http://swagger.io
servers:
  # - url: https://petstore3.swagger.io/api/v3
  - url: https://localhost:9100/api
tags:
  - name: brush
    description: Operations about brushes
    # externalDocs:
    #  description: Find out more
    #  url: http://swagger.io
  - name: pixel-grid
    description: Operations about the pixel grid 
paths:
  /brushes:
    post:
      tags:
        - brush
      summary: Create a new brush to paint the grid
      description: Create a new brush to paint the grid
      operationId: createNewBrush
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                required:
                - brushId
                properties:
                  brushId:
                    type: string
    get:
      tags:
        - brush
      summary: Get the current brushes (ids)
      description: ''
      operationId: getCurrentBrushes
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /brushes/{brushId}:
    get:
      tags:
        - brush
      summary: Get the current state of a brush
      description: ''
      operationId: getBrushInfo
      parameters:
        - name: brushId
          in: path
          description: The brush id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: a brush to be returned
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Brush'
        '400':
          description: invalid parameter supplied
        '500':
          description: service internal error
    delete:
      tags:
        - brush
      summary: Remove the specified brush
      description: ''
      operationId: destroyBrush
      parameters:
        - name: brushId
          in: path
          description: The brush id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
        '400':
          description: invalid parameter supplied
        '500':
          description: service internal error
  /brushes/{brushId}/move-to:
    post:
      tags:
        - brush
      summary: Move the specified brush to a new position on the pixel grid
      description: ''
      operationId: moveBrushTo
      parameters:
        - name: brushId
          in: path
          description: The brush id
          required: true
          schema:
            type: string
        - name: x
          in: query
          description: the new x position
          required: true
          schema:
            type: integer
        - name: y
          in: query
          description: the new y position
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
        '400':
          description: invalid parameter supplied
        '500':
          description: service internal error
  /brushes/{brushId}/select-pixel:
    post:
      tags:
        - brush
      summary: Select (paint) the pixel where the specified brush is
      description: ''
      operationId: selectPixel
      parameters:
        - name: brushId
          in: path
          description: The brush id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
        '400':
          description: invalid parameter supplied
        '500':
          description: service internal error
  /brushes/{brushId}/change-color:
    post:
      tags:
        - brush
      summary: Change the color of the specified brush
      description: ''
      operationId: changeBrushColor
      parameters:
        - name: brushId
          in: path
          description: The brush id
          required: true
          schema:
            type: string
        - name: color
          in: query
          description: The new brush color
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
        '400':
          description: invalid parameter supplied
        '500':
          description: service internal error
  /pixel-grid:
    get:
      tags:
        - pixel-grid
      summary: Get the current state of the pixel grid
      description: ''
      operationId: getPixelGridState
      responses:
        '200':
          description: successful operation
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/PixelGrid'
        '500':
          description: Service internal error
  /pixel-grid/register:
    post:
      tags:
        - pixel-grid
      summary: Register this pixel grid to a Pixel Grids Registry
      description: ''
      operationId: registerGrid
      parameters:
        - name: registryAddress 
          in: query
          description: URL of the Registry
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/PixelGrid'
        '500':
          description: Service internal error

components:
  schemas:
    Brush:
      type: object
      required:
      - brushId
      - x
      - y
      - color
      properties:
        brushId:
          type: string
        x:
          type: integer
        y:
          type: integer
        color:
          type: integer
    PixelGrid:
      type: object
      required:
      - numColumns
      - numRows
      - pixels
      properties:
        numColumns:
          type: integer
        numRows:
          type: integer
        pixel:
          type: array
          items:
            type: integer

